### ISSUE TITLE
Implement the in-game command "protect"

### ISSUE THREAD

**Issue by LakshyAAAgrawal** [LakshyAAAgrawal/Space_B__ars#14]
Implement a command, activated by "protect" and alternatively, another shortcut, which, when activated, let's the player not to be killed when encountering a "Space_B__ar" character.
The command must also have a cooldown period after activation, such that, it cannot be called more than once in a given time interval.

**Comment by BhavyaC16** [comment]
I have successfully implemented the command "shield" to activate protection against the "Space_B__ar" character and request you to please clarify the following:
1. Is an activation duration of 30 seconds and cooldown period of 90 seconds sufficient?
2. The space bar on the keyboard turns magenta-pink in colour when a "Space_B__ar" is encountered when the shield is enabled. Does space bar have to be changed to some other colour?

**Comment by LakshyAAAgrawal** [comment]
Thank you very much for working on this issue. Please open a pull request for the same.
1. Activation period of 30 seconds is too long I believe. It could be a duration less than 15 seconds.
2. No. I think that should be fine.
